### PR TITLE
Reset search text after clearing all filters

### LINKED ISSUE #1084: Clear search button is hidden after resetting filters
### Issue Overview:

firefox_tTWFR95QGw

### Reproduction Steps:
1. Navigate to https://ifixit.com/Parts
2. Search for something to return no results
3. Click on `Reset filters`
4. Notice that the clear button is hidden when going back to the search bar

### PR DESCRIPTION
**Pull request by federicobadini**
closes #1084 

This PR switch the searchBox from being and uncontrolled component to be a controlled component.
The searchQuery state is stored in a context to allow resetting it from several places

### QA

1. Visit Vercel preview
2. Check that the behaviour discussed in #1084 is working as expected

### CODE REVIEW

**Comment by jordycosta** [comment]
QA 🟢 

The search text-field is now reset after a user clicks on `Reset filters` ✔️ 

firefox_bJ6a9SuJj8

<details>
<summary> View testing procedure </summary><br>

### Testing Procedure:
1. Navigate to the [Vercel Preview](https://react-commerce-prod-git-reset-search-text-after-c-aed5d9-ifixit.vercel.app/Parts)
2. Search for a product that does not exist
3. Click on `Reset filters`
4. Ensure that the search text-field is reset

</details>

**Comment by federicobadini** [comment]
As discussed in the weekly meeting, this behaviour was also extended to the `Clear all filters` button on Desktop.

Screenshot 2023-02-06 at 23 24 09

The mobile version was left unchanged and the reason lies in the fact that on mobile, filters are in the drawer while the search field is on page. So it seemed a bit forced to clear the search field - which is not even in view - when clearing filters.

**Comment by jordycosta** [comment]
QA 🟢 

Confirmed the `Clear all filters` button will also clear the search text-field _(desktop only)_

firefox_CWDsKAKdpI

firefox_j7Gu16tXBe

File: frontend/templates/product-list/sections/FilterableProductsSection/SearchInput.tsx [hunk 1]
```diff
@@ -26,15 +27,15 @@ export const SearchInput = forwardRef<SearchInputProps, 'div'>((props, ref) => {
    const { query, refine, clear } = useSearchBox({
       queryHook: debouncedQueryHook,
    });
+   const { searchQuery, setSearchQuery } = useSearchQueryContext();
+
    const inputRef = React.useRef<HTMLInputElement>(null);
 
    const clearSearch = React.useCallback(() => {
-      if (inputRef.current) {
```
Comment (danielcliu-ifixit) [inline frontend/templates/product-list/sections/FilterableProductsSection/SearchInput.tsx:32]: Is there a reason we had this condition before but not now?

File: frontend/templates/product-list/sections/FilterableProductsSection/facets/drawer/index.tsx [hunk 2]
```diff
@@ -218,7 +218,7 @@ type ClearAllButtonProps = {
 };
 
 function ClearAllButton({ isVisible }: ClearAllButtonProps) {
-   const { refine } = useClearRefinements();
+   const { refine } = useClearRefinements({});
```
Comment (danielcliu-ifixit) [inline frontend/templates/product-list/sections/FilterableProductsSection/facets/drawer/index.tsx:221]: Is there a reason why we now have to pass a parameter? was it broken before?

**Comment by danielcliu-ifixit** [comment]
CR :v: but dev_block :v: on a few questions. If you feel like these questions shouldn't be blocking feel free to un block and merge the code looks fine to me.

File: frontend/templates/product-list/sections/FilterableProductsSection/SearchInput.tsx (hunk 1 above)
Comment (federicobadini) [reply frontend/templates/product-list/sections/FilterableProductsSection/SearchInput.tsx:32]: Before we were making an assignment on line 34, so the check was in place because we couldn't have a potentially null left-hand side. 

Now we are exploiting the ref just for setting the focus. 
We can then handle null values via the `?` operator on line 37

File: frontend/templates/product-list/sections/FilterableProductsSection/facets/drawer/index.tsx (hunk 2 above)
Comment (federicobadini) [reply frontend/templates/product-list/sections/FilterableProductsSection/facets/drawer/index.tsx:221]: No, it is just a typo that has no impact on functionality. 
If no property is overridden the hook sticks with default values.

I will clear it out to avoid any doubt

**Review by danielcliu-ifixit — APPROVED** [review]
CR :v:

**Comment by federicobadini** [comment]
I still see this as dev blocked even though it was CR'd. There is something else to fix or can I merge it?

**Comment by jordycosta** [comment]
un_dev_block 🟢 
QA 🟢 

Search text is reset when clicking `Clear all filters` or `Reset filters` ✔️ 

https://user-images.githubusercontent.com/95656772/219111180-ba40aa30-ef50-409f-9661-39583a151ed0.mp4

**Comment by danielcliu-ifixit** [comment]
> I still see this as dev blocked even though it was CR'd. There is something else to fix or can I merge it?

sorry my bad meant to un dev block it
