### PR TITLE
Fix featured products section edge case

### LINKED ISSUE #1469: RatingStar appearance misspelt
Noticed in another review: https://github.com/iFixit/react-commerce/pull/1463#discussion_r1136251096

RatingStar says `appearence` instead of `appearance`.

### LINKED ISSUE #1472: Fix featured products section bug

### PR DESCRIPTION
**Pull request by dhmacs**
closes #1472 
closes #1469 

This PR contains also some minor UI fixes

## QA

1. Open a product page preview with less than `6` featured products (e.g. [Arctic Silver Thermal Paste](https://react-commerce-git-fix-featured-products-section-d78d93-ifixit.vercel.app/products/arctic-silver-thermal-paste))
2. Verify that on desktop resolution you can still see featured products (5 columns for the Artic Silver Thermal Paste)
3. Open a product page preview with `6` or more featured products (e.g. [Repair Business Toolkit](https://react-commerce-git-fix-featured-products-section-d78d93-ifixit.vercel.app/products/repair-business-toolkit))
4. Verify that on desktop resolution up to `6` columns are shown

### CODE REVIEW

File: frontend/components/common/ProductGrid.tsx [hunk 1]
```diff
@@ -19,9 +19,19 @@ export function ProductGrid({
 }: ProductGridProps) {
    const childrenCount = React.Children.count(children);
 
-   const visibleChildrenCount = useBreakpointValue(
+   const columnsToGetAtLeastOneCompleteRow: Record<string, number> =
       Object.entries(columns).reduce((acc, [key, value]) => {
-         acc[key] = Math.floor(childrenCount / value) * value;
+         acc[key] = childrenCount < value ? childrenCount : value;
```
Comment (masonmcelvain) [inline frontend/components/common/ProductGrid.tsx:24]: Super minor: I might find `Math.min` easier to read here

```suggestion
         acc[key] = Math.min(childrenCount, value);
```

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻 Thanks!
