### PR TITLE
Routing: Don't 404 on item type visits

### LINKED ISSUE #516: Direct entry to item type product lists 404ing
Enter directly https://www.ifixit.com/Parts/iPhone_11/Adhesives and get a 404 with the following error:
image

Enter via the parent page (https://www.ifixit.com/Parts/iPhone_11) by selecting "Adhesives" in the UI, the page is displayed.

### PR DESCRIPTION
**Pull request by masonmcelvain**
Fixes a bug where a visit to /Parts/Device/Item_Type would 404. The item type slug is optional, but any extra path components after that should 404.

This bug was unintentionally introduced in https://github.com/iFixit/react-commerce/commit/c32b62fe8859fa04f68b4f6e855b0938120544fd (and I missed it in CR!).

Admittedly it was bad idea on my part to store the itemTypeHandle in an unused variable, and it got "cleaned up" in that commit. Now, we'll include it in the `...` and only 404 if there is > 1 extra path component.

## QA
Visit /Parts/iPhone_11/Adhesives and make sure it doesn't 404.

Closes #516

### CODE REVIEW

File: frontend/pages/Parts/[...deviceHandleItemType].tsx [hunk 1]
```diff
@@ -31,12 +31,14 @@ export const getServerSideProps: GetServerSideProps<AppPageProps> = async (
    );
 
    const { deviceHandleItemType } = context.params || {};
-   const [deviceHandle, ...rest] = Array.isArray(deviceHandleItemType)
+   const [deviceHandle, ...itemTypeAndRest] = Array.isArray(
+      deviceHandleItemType
+   )
```
Comment (andyg0808) [inline frontend/pages/Parts/[...deviceHandleItemType].tsx:36]: This seems odd. `isArray` returns a boolean, not an array, if I'm reading [the docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray) right. So I'm not sure how unpacking that works.

**Review by andyg0808 — CHANGES_REQUESTED** [review]

**Comment by andyg0808** [comment]
dev_block :+1: on what I suspect is a bug.

File: frontend/pages/Parts/[...deviceHandleItemType].tsx (hunk 1 above)
Comment (dhmacs) [reply frontend/pages/Parts/[...deviceHandleItemType].tsx:36]: @andyg0808 this condition is part of a ternary expression, so this instruction is actually returning an array 👍

Comment (andyg0808) [reply frontend/pages/Parts/[...deviceHandleItemType].tsx:36]: Oh, got it. Thanks.

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :dog: through ca1e87b
un_dev_block :+1:

**Review by djmetzle — APPROVED** [review]
Thanks @masonmcelvain 
LGTM CR :link:

**Comment by deltuh-vee** [comment]
QA 🎬 
Direct entry to Item Type pages no longer 404s
