### PR TITLE
Remove layout shifts

### LINKED ISSUE #411: Mobile layout shift
The model buttons are initially expanded. They collapse after the page is visible causing major layout shift. 

https://user-images.githubusercontent.com/72166715/177870522-7775d0a3-cf5c-4842-8645-d9f8c32d8cc8.mp4

Repro steps:
1. Use a mobile device and and toggle down internet speed; fast 3g will do.
2. Scroll immediately after some of the page is visible - note the long set of model buttons
3. Once the page finishes loading and the model buttons collapse, and you find yourself much farther down page

Note: 
After a couple of page reloads, the shift no longer occurs.

### PR DESCRIPTION
**Pull request by federicobadini**
closes #411 

To remove the layout shift we are now rendering all the model button elements and we are masking them adjusting the `maxHeight` of an additional external div.

#QA
1. Open the vercel preview
3. Verify that #411 is fixed (eventually throttling the connection to better inspect first load)

### CODE REVIEW

**Comment by erinemay** [comment]
QA 🔥 
- Mobile model button layout shift is gone (confirmed on on iPhone 13 Pro, Samsung Galaxy S22, iPhone 8).
- Confirmed load behavior on tablet/desktop remains unchanged.

File: frontend/components/product-list/sections/ProductListChildrenSection.tsx [hunk 1]
```diff
@@ -29,31 +25,27 @@ export function ProductListChildrenSection({
...
-      {
-         base: 4,
-         sm: 6,
-         md: 12,
-      },
-      'md'
-   );
-   const isMounted = useIsMounted();
-   const visibleChildrenCount = isMounted ? responsiveVisibleChildrenCount : 12;
+   const [showingMore, setShowingMore] = React.useState(false);
```
Comment (masonmcelvain) [inline frontend/components/product-list/sections/ProductListChildrenSection.tsx:28]: Minor: I personally like it when we prefix boolean variable names with something like `is`, `should`, `can`, etc, but this is totally fine and not worth changing.

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

File: frontend/components/product-list/sections/ProductListChildrenSection.tsx (hunk 1 above)
Comment (federicobadini) [reply frontend/components/product-list/sections/ProductListChildrenSection.tsx]: No objections. I'm changing it in `isShowingMore`.

File: frontend/components/product-list/sections/ProductListChildrenSection.tsx [hunk 2]
```diff
@@ -25,18 +25,18 @@ export function ProductListChildrenSection({
       childrenHeading,
       children: productListChildren,
    } = productList;
-   const [showingMore, setShowingMore] = React.useState(false);
+   const [isShowingMore, setShowingMore] = React.useState(false);
```
Comment (masonmcelvain) [inline frontend/components/product-list/sections/ProductListChildrenSection.tsx:28]: If we're gonna change the name of the var, let's change the name of the setter to `setIsShowingMore` too just to be consistent

**Review by masonmcelvain — CHANGES_REQUESTED** [review]
CR ✌🏻 thanks for the change! One more little nitpick, sorry 😅

**Comment by masonmcelvain** [comment]
In the interest of moving things along, I'm going to merge this as is. Thanks @federicobadini!

**Review by masonmcelvain — APPROVED** [review]

File: frontend/components/product-list/sections/ProductListChildrenSection.tsx (hunk 2 above)
Comment (federicobadini) [reply frontend/components/product-list/sections/ProductListChildrenSection.tsx:28]: I'll apply the rename in one of my next PR
