### PR TITLE
Add temporary fix to avoid page crash

### LINKED ISSUE #345: Patch Algolia SSR re-render bug

### PR DESCRIPTION
**Pull request by dhmacs**
closes #345 

## Changelog

- Move InstantSearch provider up in the component tree hierarchy to avoid unnecessary re-renders
- Force InstantSearch provider to unmount when it re-render, so that internals do not get stuck in a broken state

## QA

1. Visit the Vercel PR preview (replace vercel.app with cominor.com)
2. Browse trough product lists, use refinements, use the browser back button and verify that the product list page does not break

### CODE REVIEW

**Comment by dhmacs** [comment]
dev_block 🛑

**Comment by dhmacs** [comment]
un_dev_block 🟢

**Review by sterlinghirsh — APPROVED** [review]

**Comment by sterlinghirsh** [comment]
CR :zap:

File: frontend/components/common/InstantSearchProvider.tsx [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+      <InstantSearchSSRProvider {...serverState}>
+         {provider}
+      </InstantSearchSSRProvider>;
+   }
+   return provider;
+}
+
+function useCountRenders() {
+   const countRef = React.useRef(0);
+   countRef.current++;
```
Comment (danielbeardsley) [inline frontend/components/common/InstantSearchProvider.tsx:113]: Clever!

**Review by danielbeardsley — APPROVED** [review]
CR :+1: 

Nice work! Good job on fixing the bug and extracting the instant search into a separate component.

**Comment by erinemay** [comment]
@dhmacs 
QA 🌡️ 

Was able to reproduce the page crash due to instantsearch on the main branch.  

Attempted to reproduce the error on this branch without success: 

- Applied selected facets (15+)
- Used the back and forward buttons
- Quickly navigated back and forth between parents and children
- Used search terms with and without the facets
- Reloaded the page

Tried on Chrome and FF and was not able to reproduce the error.
