### PR TITLE
Product List Items: Fix decimal display

### LINKED ISSUE #886: Fix decimal point display
As a pro user, the trailing 0 on the price is truncated: https://react-commerce.vercel.app/Parts?q=macbook%20battery
image

### PR DESCRIPTION
**Pull request by masonmcelvain**
Reuses the `ProductPrice` component in our collections to consistently render product prices. Fixes a bug where trailing zeros weren't rendered in discounted prices.

## QA

Visit collection pages with and without discounts, and make sure prices are rendered correctly and the UI looks ok.

Also do this as a pro user.

Closes #886

### CODE REVIEW

**Comment by erinemay** [comment]
deploy_block ❓ Did we used to have a pro flair that went on the collection pages? 
1. I'm not sure if changing just the price to orange is an experience improvement.
2. Also, it looks like the product card layout is different here. The discounted price is now next to the original price instead of above.
<details><summary>Screenshots for those two things⬆️ </summary>

Branch
image

Main
image



</details>

dev_block 🛑 It looks like we lost the discount pricing on this item, but didn't lose the discount flair. 

<details><summary>Missing discount price while logged in as a pro user:</summary>

On `/Parts?q=macbook%20battery`

This branch
image

Main
image

</details>

All this is seen by logging in as a pro user and going to https://react-commerce-git-collections-discount-price-ifixit.vercel.app/Parts?q=macbook%20battery. As a non-pro user I can't see any of the pro discounts ✔️

**Comment by erinemay** [comment]
We've also swapped orientation of pricing differences in the block layout. I think it looks better on master. See # 3 below.

So, to summarize this with my previous comment:
1. I'm not sure if changing just the price to orange is an experience improvement.
<details><summary>2. On mobile and desktop list view, the prices are now side by side instead of aligned vertically</summary>


Branch
image

Main
image



</details>

<details><summary>3. On mobile and desktop grid view, prices were horizontally aligned already, but the original and discounted prices have swapped places</summary>


| Branch | Master |
| - | - |
| image | image |


</details>

4. Missing the discount price as noted https://github.com/iFixit/react-commerce/pull/964#issuecomment-1298907547

**Comment by masonmcelvain** [comment]
> Did we used to have a pro flair that went on the collection pages?

I think that flair is for product groups that contain a pro-only product. It won't show up for normal products that pros have a discount on.

We _could_ show a pro badge for discounted pro products like we do on the product page. However, on pro only products, customers would see both the pro flair and the pro badge.

image

**Comment by masonmcelvain** [comment]
> Missing discount price while logged in as a pro user:

I think this is for 0% discounts only, and it likely also affects normal users. I can fix it tho.

**Comment by masonmcelvain** [comment]
Waiting for feedback on:

- Should we hide the pro badge (the one next to the price, not the pro flair) on the collection page?
- Should we hide 0% discounts?

**Comment by masonmcelvain** [comment]
> It looks like we lost the discount pricing on this item, but didn't lose the discount flair.

Actually, based on this sentence, it sounds like it's ok to hide 0% discounts.

**Comment by erinemay** [comment]
> > It looks like we lost the discount pricing on this item, but didn't lose the discount flair.
> 
> Actually, based on this sentence, it sounds like it's ok to hide 0% discounts.

Yeah. In this case, we should hide both or neither, and I vote both. 

>Should we hide the pro badge (the one next to the price, not the pro flair) on the collection page?

⚠️ This is pretty out of scope for fixing the decimal display, but in response to your question:

I think we should show it and change the % off discount flair color to orange. We should stick to one convention for each user type. Pros should see pro pricing and only their own color scheme (orange). 

<details><summary>Pro vs regular user with the latest changes</summary>

| Pro | Regular user |
| - | - |
| image | image |
| image | image |
| image | image |

Images from these URLs:
- https://react-commerce-git-collections-discount-price-ifixit.vercel.app/Parts?q=macbook%20battery
- https://react-commerce-git-collections-discount-price-ifixit.vercel.app/Tools?q=business%20repair

</details>

I think all these changes should be done at once. I don't love the half orange half red pro experience. I'm not sure about design, but if the crossed out discount and percent off flair are uniform (both orange), I imagine the pro flair could live next to either of those elements and be fine. 
image

**Comment by dhmacs** [comment]
> I think that flair is for product groups that contain a pro-only product. It won't show up for normal products that pros have a discount on.

@masonmcelvain Seems like that's not the case. The flair should apply to any discounted products for pro users

image

**Comment by masonmcelvain** [comment]
@dhmacs I think we may be talking about different components.

When I've referred to "pro flair", I intended to reference this component on product list items:

https://github.com/iFixit/react-commerce/blob/9962828310f3c3562926e50991d08a5e598faa99/frontend/templates/product-list/sections/FilterableProductsSection/ProductList.tsx#L169-L173

https://github.com/iFixit/react-commerce/blob/9962828310f3c3562926e50991d08a5e598faa99/frontend/templates/product-list/sections/FilterableProductsSection/ProductList.tsx#L57

(Note that `ProductSearchHit.is_pro` is `1` if a product group has any variants that are pro only products, and `0` otherwise)

When I've referred to "pro badge", I intended to reference the pro badge in the context of `<ProductPrice>`.

**Comment by masonmcelvain** [comment]
The product list item discount flair color should now be consistent with the color of the price text. I think all the QA concerns should now be addressed, lmk if not.

un_dev_block ✌🏻 un_deploy_block ✌🏻

**Review by sterlinghirsh — APPROVED** [review]
CR :zap:

**Comment by erinemay** [comment]
All in all, looks good.  
Confirmed:
- Decimal point display is fixed (can be seen fixed on /Parts/iPhone/Screen_Protectors logged in as a pro user)
- Mobile has the same similarities/differences as desktop
- Pro discount ui is uniform (all in orange, pro flair clearly indicating pro discount)

dev_block ❓ on pros seeing the pro flair and pro discount indicators even if it's just for a sale price that everyone sees. 
Details:
- URL: https://react-commerce-git-collections-discount-price-ifixit.vercel.app/Parts/iPhone/Batteries
- Context: When there's a sale, and that sale price is lower than the pro price, pros see that sale price. This is correct as they should see the lowest price available. This behavior is the same as on main.
- The problem: When they see that sale price, it's displayed as the pro price (in orange with pro flair). Comparing images E and G shows the iPhone 6s Plus battery and its sale price (that everyone gets). BUT it's displayed to pros as a pro discount (it is not the pro price - the pro price for this item is higher). Note the next product (connector bracket) is not on sale. It is displaying the pro discount price and correctly labeling it as a pro discount.)
- Implications: They're seeing the correct price that should be displayed to them (the lowest available), so they're not missing out on a discount, but I imagine when a sale ends, they might not understand why their pro price jumped up again instead of understanding that it was a sale.
- What I think should be expected: Logged in as a pro:
   - If the discount I'm seeing is a pro discount (or identical to the sale price) - label it as pro and make everything orange.
   - If the discount I'm seeing is a sale price (and the pro price I would be seeing if it weren't for the sale is higher), don't show the pro label and make everything red like the regular discount it is. 

<details><summary>(A-D) RBT on collection pages - on sale, but pro price overrides sale price ✔️ </summary>

<details><summary>A. RBT - regular user - desktop - list view - identical to main</summary>

image

</details>

<details><summary>B. RBT - regular user - desktop - tile view - identical to main</summary>

image

</details>

<details><summary>C. RBT - pro user - desktop - list view </summary>

| Context | Image  |
| - | - |
| Branch | image |
| Main | image |

</details>

<details><summary>D. RBT - pro user - desktop - tile view </summary>

| Context | Image  |
| - | - |
| Branch | image |
| Main | image |

</details>

</details>

<details><summary>(E-H) /Parts/iPhone/Batteries - some sale, some pro products ❌ </summary>

<details><summary>E. /Parts/iPhone/Batteries - regular user - desktop - list view - identical to main </summary>

image

</details>

<details><summary>F. /Parts/iPhone/Batteries - regular user - desktop - tile view - identical to main</summary>

image

</details>

<details><summary>G. /Parts/iPhone/Batteries - pro user - desktop - list view </summary>

| Context | Image  |
| - | - |
| Branch | image |
| Main | image |

</details>

<details><summary>H. /Parts/iPhone/Batteries - pro user - desktop - tile view </summary>

| Context | Image  |
| - | - |
| Branch | image |
| Main | image |

</details>

</details>

**Comment by erinemay** [comment]
Adding this here for posterity: 

I was looking at the pro pricing [field in Akeneo](https://akeneo.cominor.com/#/enrich/product/18492), but the collection pages pull from Algolia. The two were out of sync. 
According to the current prices in [Algolia](https://www.algolia.com/apps/XQEP3AD9ZT/explorer/browse/dev_product_group_en?query=iphone%206s%20plus%20replacement%20battery&page=1&searchMode=search), [this](https://github.com/iFixit/react-commerce/pull/964#issuecomment-1302440459) is behaving as expected (pro price = sale price -> pro sees it as a pro price).
<details><summary>Algolia pricing</summary>

image

</details>

I still want to make sure the case where a sale price is cheaper than the pro price works. The pro should see it as a regular sale (red/no pro icon) and not a pro price (orange/pro icon). 

To update the iPhone 6s Plus battery appearance on the [collection page](https://react-commerce-git-collections-discount-price-ifixit.vercel.app/Parts/iPhone/Batteries), and verify that case:
1. Make sure the product is set up in Akeneo: Sale price cheaper than pro price.
2. Update Algolia ⬇️ 

From Mason on updating Algolia so it matches Akeneo:
> Running them all takes a little while, but not too long. It's instant to update one at a time if you know the objectid of the one you want to update.
Command to update all products in `algolia: algolia.php sync --index product_group_en`
Command to update a given objectid in algolia: `algolia.php add --index 0000000002_product_group_3150070000_en`
image

**Comment by erinemay** [comment]
dev_block 🧷 

Ok, I followed those steps and saved it. It looks like pro users aren't getting the regular discount. 
This is logged in as a pro user 
image
This is logged out
image

<details><summary>Algolia for this product</summary>
https://www.algolia.com/apps/XQEP3AD9ZT/explorer/browse/dev_product_group_en?query=iphone%206s%20plus%20replacement%20battery&page=1&searchMode=search

image

</details>

**Comment by erinemay** [comment]
Actually, it looks like this is an issue on main as well.

I'll write up a separate issue.

**Comment by erinemay** [comment]
So QA 👍 
- Decimal point display is fixed (can be seen fixed on /Parts/iPhone/Screen_Protectors logged in as a pro user)
- Mobile has the same similarities/differences as desktop
- Pro discount ui is uniform (all in orange, pro flair clearly indicating pro discount)
- Amounts displayed reflect amount in cart

Overall, there is no differences in prices shown to users (pro or not) on collection pages between this branch and master. Sample urls:
   - https://react-commerce-git-collections-discount-price-ifixit.vercel.app/Tools?q=repair
   - https://react-commerce-git-collections-discount-price-ifixit.vercel.app/Parts/iPhone/Batteries?q=iphone%20

The differences are:
- When a pro user is logged in and their pro discount is the same as or less than the price for regular users, they see their appropriate discount (unchanged from master), and they see the orange and pro flair (change from master).
- No longer showing discount indicator if 0% discount

https://github.com/iFixit/react-commerce/issues/992 is present on master

File: frontend/templates/product-list/sections/FilterableProductsSection/useProductSearchHitPricing.ts [hunk 1]
```diff
@@ -29,16 +31,31 @@ export function useProductSearchHitPricing(
 
    const price = proTierPrice ?? product.price_float;
```
Comment (masonmcelvain) [inline frontend/templates/product-list/sections/FilterableProductsSection/useProductSearchHitPricing.ts:32]: I think this is causing the pro price to always be preferred, even if it's greater than the price that is available to all other users.

**Comment by masonmcelvain** [comment]
Thanks @erinemay! Going to merge this and address that issue in a new pull
