### PR TITLE
Fix no safe guard against long search query

### LINKED ISSUE #101: Bug: No safe-guard against long search query
# Description:

While QAing https://github.com/iFixit/react-commerce/pull/97 I realized that I did not test a long entry for the search field in https://github.com/iFixit/react-commerce/pull/94. This is an issue since the search query is added to the url as a parameter, therefore, if the search query is long it seems to cause an internal server error.

https://user-images.githubusercontent.com/22064420/136464932-07170a7b-e324-469c-921a-0a4a4a855a35.mp4

# Reproduction Steps:
1. Go the product search field
2. Enter an absurd amount of text
3. Reload the page
4. Notice there `500` error that is displayed

# Expected Behavior

I am not sure what should be the expected behavior on this (i.e. limit the amount of characters we can search, not have the search text added to the url, etc.) however, I do expect that we should safe-guard or prevent this from occurring.

### PR DESCRIPTION
**Pull request by dhmacs**
This PR closes #101 

## Changelog

- Prevents user from inserting long search queries into the search field

## QA

1. Visit the Vercel PR preview
2. Visit parts product list page and verify that the product list search input is bounded

### CODE REVIEW

**Comment by GrantMatejka** [comment]
CR 🌽

**Comment by deltuh-vee** [comment]
QA 🎬 
A search query longer than 100 characters cannot be entered.

File: frontend/features/productList/components/sections/FilterableProductsSection/SearchInput.tsx [hunk 1]
```diff
@@ -38,7 +53,7 @@ export const SearchInput = chakra(({ className }: SearchInputProps) => {
                bg="white"
                placeholder="Search"
                tabIndex={0}
-               onChange={(event) => search(event.currentTarget.value)}
+               onChange={onSearchChange}
```
Comment (evannoronha) [inline frontend/features/productList/components/sections/FilterableProductsSection/SearchInput.tsx:56]: Why the added complexity instead of just using a `maxLength` prop?

**Review by evannoronha — APPROVED** [review]
CR 🔥  ... with a question.

File: frontend/features/productList/components/sections/FilterableProductsSection/SearchInput.tsx (hunk 1 above)
Comment (dhmacs) [reply frontend/features/productList/components/sections/FilterableProductsSection/SearchInput.tsx]: That's right, much more elegant solution! I've also removed the callback memoization as probably isn't doing that much

**Comment by deltuh-vee** [comment]
Carry over QA 🎬

**Comment by jande141** [comment]
CR :poultry_leg:

**Comment by GrantMatejka** [comment]
CR 🌽
