### PR TITLE
Instantsearch: Handle typos in Strapi productlist filters

### LINKED ISSUE #1399: Better error handling on typo'd ProductList filter
## Problem
When a ProductList in Strapi has a `filter` with a syntax error, the page crashes hard. At time of writing, https://www.ifixit.com/Tools/Xbox_Series_X_Wireless_Controller renders like 
image

The `filter` string is:
```
(identifiers: 'IF145-472' OR 
identifiers: 'IF145-348' OR 
identifiers: 'IF145-335' OR 
(identifiers: 'IF145-077' OR 
identifiers: 'IF145-523' OR 
identifiers: 'IF145-307' OR 
identifiers: 'IF145-364' OR 
identifiers: 'IF317-092' OR 
identifiers: 'IF145-106' OR 
identifiers: 'IF145-238' OR 
identifiers: 'IF145-002' OR 
identifiers: 'IF145-027' OR 
identifiers: 'IF145-020') 
```
Note the extra `(` on the fourth line. It's probably not possible to catch this before saving the ProductList without a lot of extra work, but we should handle it more gracefully on the frontend.

## Do This
Catch the error that's presumably coming from Algolia, report a useful message in the console, show a no-results or error page.

### PR DESCRIPTION
**Pull request by masonmcelvain**
Closes #1399

Renders productlist pages with typos in their Strapi instantsearch filter instead of 500ing. The misconfiguration in Strapi is reported to Sentry.

## QA
- Add an invalid filter to a productlist on this branch's [strapi instance](https://handle-productlist-filter-typos.govinor.com/admin).
  - For example, on add the following filter to this [productlist](https://handle-productlist-filter-typos.govinor.com/admin/content-manager/collectionType/api::product-list.product-list/461?plugins[i18n][locale]=en).
```
(identifiers: 'IF145-472' OR 
identifiers: 'IF145-348' OR 
identifiers: 'IF145-335' OR 
(identifiers: 'IF145-077' OR 
identifiers: 'IF145-523' OR 
identifiers: 'IF145-307' OR 
identifiers: 'IF145-364' OR 
identifiers: 'IF317-092' OR 
identifiers: 'IF145-106' OR 
identifiers: 'IF145-238' OR 
identifiers: 'IF145-002' OR 
identifiers: 'IF145-027' OR 
identifiers: 'IF145-020') 
```
- Visit the affected productlist page (`/Tools/Xbox_Series_X_Wireless_Controller`), and note that the page renders just fine. The error will get logged in the vercel logs, and should get reported to the react-commerce-dev sentry project.

CC @sterlinghirsh

### CODE REVIEW

**Comment by sterlinghirsh** [comment]
I'm glad we can handle this, though I'm nervous that there's now no editor-facing feedback that there's a bug in their filter. I see that we're reporting to Sentry, but at best, devs will see that. We could have a user-visible (or admin-visible) message, though even better would be a strapi plugin or something that validates the filter in real time. We haven't done a slack message from react-commerce yet, but if the user-facing message is too complicated, that could be an option.

**Comment by danielbeardsley** [comment]
> there's now no editor-facing feedback that there's a bug in their filter.

I gave it a go, tell me what you think. @masonmcelvain, feel free to cherry-pick this commit:

https://github.com/iFixit/react-commerce/compare/algolia-error-admin-message

image

**Comment by masonmcelvain** [comment]
> even better would be a strapi plugin or something that validates the filter in real time

That would be fun to work on, but I don't want to do it in this issue. Turns it from a 1 into a 3

> We haven't done a slack message from react-commerce yet, but if the user-facing message is too complicated, that could be an option.

Since Danny wrote the code I'll do the ui notification. dev_block ✌🏻 on integrating it

**Comment by masonmcelvain** [comment]
un_dev_block :v:

**Review by danielbeardsley — APPROVED** [review]
CR :+1:

**Comment by deltuh-vee** [comment]
QA 🎬 
* Product pages with invalid filters can still render.
* The error still gets reported to Sentry.

File: frontend/templates/product-list/server.tsx [hunk 1]
```diff
@@ -215,6 +213,48 @@ export const getProductListServerSideProps = ({
...
+   };
+   try {
+      return { serverState: await tryGetServerState(productList) };
+   } catch (e) {
+      console.error('Error getting instantsearch server state', e);
+      Sentry.withScope((scope) => {
+         scope.setExtra('Productlist', productList);
+         scope.setExtra('Filters from Strapi', productList?.filters);
+         Sentry.captureException(e);
+      });
```
Comment (masonmcelvain) [inline frontend/templates/product-list/server.tsx:245]: Oops, I forgot to drop the code that reports to Sentry now that we're rendering a notice on the ui. I'll open another pull.

Comment (masonmcelvain) [reply frontend/templates/product-list/server.tsx:245]: https://github.com/iFixit/react-commerce/pull/1571
