### PR TITLE
localStorage: require a schema validator

### LINKED ISSUE #1656: localStorage: Can we do zod schema validation on value when they come out of cache?
From Post-Mortem: #1653

### Problem
We cached user data in local storage. The schema changed, the cached values didn't match the new schema, but we don't do validation, so the result was an exception when our components used the data. The exception caused a blank page until you refreshed

### Do This
It's a good idea to make a similar schema-validating cache layer for localStorage so that changing the schema will invalidate the cache and we won't have to remember to bump a cache key.

Definitely add validation. Maybe implement a custom solution instead of zod if the bundle size increase is significant.

### PR DESCRIPTION
**Pull request by danielbeardsley**
Now corrupt values in localStorage won't be used if they don't pass the validator (which is required to return the same type as the data or null).

Closes #1656

### CODE REVIEW

File: packages/ui/hooks/index.ts [hunk 1]
```diff
@@ -153,8 +154,9 @@ export function useExpiringLocalPreference<Data = any>(
             const expiresAt = Number.isInteger(data?.expires)
                ? data.expires
                : 0;
-            if (expiresAt && Date.now() < expiresAt) {
-               setData(data?.value);
+            const validData = validator(data?.value);
+            if (validData !== null && expiresAt && Date.now() < expiresAt) {
+               setData(validData);
```
Comment (danielcliu-ifixit) [inline packages/ui/hooks/index.ts:159]: we could treat the validator returning anything besides null as valid and then `setData(data?.value)` so we wouldn't need the ternary operations in the validators anymore

File: packages/ui/hooks/index.ts [hunk 2]
```diff
@@ -183,16 +185,19 @@ export function useExpiringLocalPreference<Data = any>(
...
 
    React.useEffect(() => {
       try {
          const serializedData = localStorage.getItem(key);
          if (serializedData != null) {
-            const data = JSON.parse(serializedData);
-            setData(data as Data);
+            const data = validator(JSON.parse(serializedData));
+            if (data !== null) {
+               setData(data as Data);
```
Comment (danielcliu-ifixit) [inline packages/ui/hooks/index.ts:199]: do we need this type validation still if we have a validator?

**Review by danielcliu-ifixit — DISMISSED** [review]
CR :v: but left some small suggestions

File: packages/ui/hooks/index.ts (hunk 2 above)
Comment (danielbeardsley) [reply packages/ui/hooks/index.ts:199]: You're right, we don't!

File: packages/ui/hooks/index.ts (hunk 1 above)
Comment (danielbeardsley) [reply packages/ui/hooks/index.ts:159]: I don't really understand, it seems like what we're doing here: 

```
if (validData !== null) { setData(data) }
```

Comment (danielcliu-ifixit) [reply packages/ui/hooks/index.ts:159]: sorry what i meant to propose is having the validators return a boolean value so like instead of 
```php
data === ProductViewType.List || data === ProductViewType.Grid
            ? data
            : null
```

we could just have 
```php
data === ProductViewType.List || data === ProductViewType.Grid
```

**Review by danielcliu-ifixit — APPROVED** [review]
CR :v:

File: packages/ui/hooks/index.ts (hunk 1 above)
Comment (danielbeardsley) [reply packages/ui/hooks/index.ts:159]: Oh, I forgot that typescript can do assertion functions...,..

Update: I tried but I couldn't get typescript to enforce that the validator function was checking the type. It's easier to enforce that it returns the right type.


For instance, using a validator type of:
`validator: (data: any) => data is Data`
and a validation function of:
`(data: any): data is ProductViewType => data`

Results in typescript not complaining. It apparently doesn't validate that your assertion function actually asserts anything.

**Comment by deltuh-vee** [comment]
QA 🎬 
Invalid data in Local Storage no longer crashes the page.
