### PR TITLE
Fix defaultShowAllChildrenOnLgSizes regression

### LINKED ISSUE #1402: Fix defaultShowAllChildrenOnLgSizes regression
defaultShowAllChildrenOnLgSizes behaviour was partially incorrect since it should show all children **only on `>= lg` screen sizes**.

With #1361 this behaviour was wrongly removed.

### PR DESCRIPTION
**Pull request by federicobadini**
closes #1402 

### QA

1. Visit [Vercel preview](https://react-commerce-git-fix-regression-default-show-al-a7a976-ifixit.vercel.app/Parts)
2. Verify that enabling the `defaultShowAllChildrenOnLgSizes` flag in [Strapi](https://fix-regression-default-show-all-children-on-lg-size.govinor.com/admin/), all the associated product list page children are shown on `lg` screen.
3. On screen size `< lg` children should still show only after interaction

### CODE REVIEW

File: frontend/templates/product-list/sections/ProductListChildrenSection.tsx [hunk 1]
```diff
@@ -135,17 +138,32 @@ const computeChildVisibility = (
...
       md: totalCount <= 9 ? 'block' : position < 8 ? 'block' : 'none',
-      lg: totalCount <= 8 ? 'block' : position < 7 ? 'block' : 'none',
-      xl: totalCount <= 10 ? 'block' : position < 9 ? 'block' : 'none',
+      lg: defaultShowAllChildrenOnLgSizes
+         ? 'block'
+         : totalCount <= 8
+         ? 'block'
+         : position < 7
+         ? 'block'
+         : 'none',
```
Comment (masonmcelvain) [inline frontend/templates/product-list/sections/ProductListChildrenSection.tsx:147]: I find using `||` is easier to read than a nested ternary, but what you have looks correct and I'm not going to block on this.

```suggestion
      lg: defaultShowAllChildrenOnLgSizes || totalCount <= 8 || position < 7
         ? 'block'
         : 'none',
```

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻 Good catch!

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻 Thanks for the change!

**Comment by deltuh-vee** [comment]
QA 🎬 
With `defaultShowAllChildrenOnLgSizes` enabled,  all product list children are only shown at`lg` screen sizes.
