### PR TITLE
Mock buybox api and improve tests

### LINKED ISSUE #987: Fix add to cart failing due to buybox api
When running tests from a location different from US, add to cart tests fails because the ui shows the buy box instead of the add to cart button

## Do this

Mock the buy box api

### PR DESCRIPTION
**Pull request by dhmacs**
closes #987 

## Changelog

- Drop unused Cypress config (and moved `experimentalSessionAndOrigin` to the actual config file)
- Add a commands for Cypress compatible loops
- Fixed issue described by #987 
- Cleaned up add to cart tests

## QA

I think it's not necessary, as this changes only affects CI

### CODE REVIEW

**Review by danielbeardsley — APPROVED** [review]
CR :+1:

File: frontend/test/cypress/support/index.d.ts [hunk 1]
```diff
@@ -3,6 +3,13 @@
 declare namespace Cypress {
    interface Chainable {
       isWithinViewport(): Chainable<JQuery<HTMLElement>>;
+      /**
+       * This command simulates the behavior of a foor loop in a way that is compatible with Cypress asyncronous commands.
+       * Read more here https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#Avoid-loops
+       * @param {number} times
+       * @param {(index: number) => void} callback
+       */
+      times(times: number, callback: (index: number) => void): Chainable;
```
Comment (masonmcelvain) [inline frontend/test/cypress/support/index.d.ts:12]: Nice thanks for finding these docs and adding this utility

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by masonmcelvain** [comment]
I don't think this needs QA since it's test-only
