### PR TITLE
Fix Algolia popstate bug

### LINKED ISSUE #352: Navigating down and up device hierarchy with selected facets renders incorrect page
### Repro steps
1. Go to a parent category like https://react-commerce.vercel.app/Parts/iPhone
2. Select a few facets
3. Go into one of its child device categories via the UI (like https://react-commerce.vercel.app/Parts/iPhone_12_mini)
4. Go back (back button) and note that the rendered page is not the expected parent page
    - URL is correct
    - Rendered page appears to be the child page, but without products

<details><summary>Screen-recording</summary>

https://user-images.githubusercontent.com/72166715/174849987-29f4236d-6013-43c6-ab96-1347f2b9160b.mp4

</details>

### Additional details
Found during testing of https://github.com/iFixit/react-commerce/pull/351, but noted it was also present on the main branch.

### PR DESCRIPTION
**Pull request by dhmacs**
fixes #352 

## QA

1. Visit Vercel Preview
2. Verify that the bug described by #352 is fixed

### CODE REVIEW

File: frontend/components/common/InstantSearchProvider.tsx [hunk 1]
```diff
@@ -100,12 +124,6 @@ export function InstantSearchProvider({
          </InstantSearch>
       </InstantSearchSSRProvider>
    );
-   if (routing) {
-      <InstantSearchSSRProvider {...serverState}>
-         {provider}
-      </InstantSearchSSRProvider>;
-   }
-   return provider;
```
Comment (masonmcelvain) [inline frontend/components/common/InstantSearchProvider.tsx:108]: This is also deleted in #359, but the changes look the same 👍🏻

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻
