### PR TITLE
Bug: Fix repeated facets

### LINKED ISSUE #698: Collections: Bug: /Hard_Drives_ Item Type
Seems like maybe we added an additional Hard Drives Item Type facet on accident. For example, https://www.ifixit.com/Parts/iMac_Intel_17%22/Hard_Drives_.

image

I don't know how prevalent this is but we should find out and then fix it. @erinemay

### PR DESCRIPTION
**Pull request by sumukhipandey**
Previously, we  had some repeated facets being displayed. Although I don't know if this is the solution we are looking for here but this PR basically makes sure that we do not display any facets that have an `item.count` of 0.

## QA:
- Visit the preview and add `/Parts/iMac_Intel_17"/Hard_Drives_` 
- Make sure there are no repeated facets as mentioned in the issue.

Closes #698 

CC: @erinemay @sterlinghirsh

### CODE REVIEW

**Comment by dhmacs** [comment]
Seems like we're trying to cure the symptoms and not the disease. I'd try to understand why we have repeated items and how we can prevent that. Also `useRefinementList` isn't supposed to send back `0` count items I think, so I wonder how we end up having this

**Comment by jordycosta** [comment]
QA 🟢 

No longer seeing duplicate facets

[https://react-commerce-prod-git-bug-fix-repeated-facets-ifixit.vercel.app/Parts/iMac_Intel_17%22/Hard_Drives_](https://react-commerce-prod-git-bug-fix-repeated-facets-ifixit.vercel.app/Parts/iMac_Intel_17%22/Hard_Drives_)

---

**Comment by sterlinghirsh** [comment]
dev_block :zap: I'm not seeing this bug either. Maybe it was bad data or another bug that got fixed already, but unless we have a repro, I don't want to merge this change. I agree with @dhmacs that if we're seeing this bug, we should figure out what that is rather than adding a bandaid fix that will stick around forever and cover up deeper problems. If we're not seeing the bug anymore, then let's move on and not worry about it.

**Comment by erinemay** [comment]
@sterlinghirsh it's a weird url https://github.com/iFixit/react-commerce/issues/698#issuecomment-1260163346

**Comment by sterlinghirsh** [comment]
Ah okay. Looks like any item type with an underscore will do this. There's another bug here for sure that is causing it to get added to the list, so if we're going to fix it, let's fix it there rather than filtering it out later.

**Comment by sumukhipandey** [comment]
un_dev_block 🦋  on 725cd864b68bb5afbb91a9386b4bccd1609b6279
@sterlinghirsh @dhmacs I wasn't sure if there was a cleaner and better solution to this and/or if this is where we want to address the bug. I am un dev blocking for right now.

File: frontend/templates/product-list/sections/FilterableProductsSection/RefinementMultiSelect.tsx [hunk 1]
```diff
@@ -68,28 +68,31 @@ const MultiSelectItem = React.memo(function MultiSelectItem({
...
-            size="sm"
-            fontFamily="sans-serif"
-            color="gray.500"
-            fontWeight={isRefined ? 'bold' : 'inherit'}
-         >
-            {item.count}
-         </Text>
-      </HStack>
-   );
+   if (item.count > 0) {
```
Comment (sterlinghirsh) [inline frontend/templates/product-list/sections/FilterableProductsSection/RefinementMultiSelect.tsx:71]: Let's get rid of these ifs since we should be operating under the assumption that nothing should show up with item.count = 0 and this will hide it if that breaks.

File: frontend/components/common/InstantSearchProvider.tsx [hunk 2]
```diff
@@ -174,7 +174,11 @@ export function InstantSearchProvider({
                .split('/')
                .filter((part) => part !== '');
             const deviceHandle = pathParts.length >= 2 ? pathParts[1] : '';
-            const itemType = pathParts.length >= 3 ? pathParts[2] : '';
+            let itemType = pathParts.length >= 3 ? pathParts[2] : '';
+
+            if (itemType.endsWith('_')) {
+               itemType = itemType.substring(0, itemType.length - 1);
+            }
```
Comment (sterlinghirsh) [inline frontend/components/common/InstantSearchProvider.tsx:181]: I'm not 100% sure what's going on with the itemType here. Does using an itemType in the filterObject cause it to be added to the facets list? I could see Algolia doing that just to show the selected facet even if it's 0, though it is a little odd. Maybe our own code is doing that in the place where we filter facet options? I'm not sure. In any case, I think a cleaner way to accomplish this is to leave the itemType as a const, but down on line 192 when we destylizeDeviceItemType, we can add a .trim() call like `destylizeDeviceItemType(decode...).trim()` will drop any leading or trailing whitespace.

**Comment by sumukhipandey** [comment]
un_dev_block 🦋  on 503da96d26a0f2e1a458a6b4a8ccccdd18913412 and d8e2412efef6e68936c1fd6462b0c5b09fccfafd

File: frontend/templates/product-list/sections/FilterableProductsSection/RefinementMultiSelect.tsx (hunk 1 above)
Comment (sumukhipandey) [reply frontend/templates/product-list/sections/FilterableProductsSection/RefinementMultiSelect.tsx]: Resolved d8e2412efef6e68936c1fd6462b0c5b09fccfafd

File: frontend/components/common/InstantSearchProvider.tsx (hunk 2 above)
Comment (sumukhipandey) [reply frontend/components/common/InstantSearchProvider.tsx]: Resolved 503da96d26a0f2e1a458a6b4a8ccccdd18913412

**Comment by danielcliu-ifixit** [comment]
CR :v:

File: frontend/templates/product-list/sections/FilterableProductsSection/RefinementMultiSelect.tsx [hunk 3]
```diff
@@ -92,4 +92,5 @@ const MultiSelectItem = React.memo(function MultiSelectItem({
          </Text>
       </HStack>
    );
+   return null;
```
Comment (danielcliu-ifixit) [inline frontend/templates/product-list/sections/FilterableProductsSection/RefinementMultiSelect.tsx:95]: do we need these return nulls?

Comment (sumukhipandey) [reply frontend/templates/product-list/sections/FilterableProductsSection/RefinementMultiSelect.tsx]: Thanks for pointing it out! You are right we do not need these anymore.
Resolved 5e36b200fbc107858ffc45e7501bab9f0d45b083

**Comment by sumukhipandey** [comment]
un_dev_block 🦋 on 5e36b200fbc107858ffc45e7501bab9f0d45b083

**Comment by danielcliu-ifixit** [comment]
CR :v:

**Comment by erinemay** [comment]
QA 👍 
- item type collections with a trailing underscore now strip the underscore and loads without it
- there are no repeating item type facets
- item type filters with other filters still work
- refreshing with filters leaves the filters in place

**Review by danielcliu-ifixit — APPROVED** [review]
